python:
- "2.7"

env:
- TESTING=true DATABASE_URL=postgresql://localhost/recordtrac

install: 
- sudo pip install -r requirements.txt

before_script:
- psql -c 'create database recordtrac;' -U postgres

script:
- python tests.py