ACKNOWLEDGEMENT_DAYS_DUE = 5

event_type = {
    "user_added": "user_added",
    "user_permissions_changed": "user_permissions_changed",
    "user_information_edited":,
    "request_created",
    "request_acknowledged",
    "request_status_changed",
    "request_extended",
    "request_closed",
    "request_title_edited",
    "request_agency_description_edited",
    "request_title_privacy_edited",
    "request_agency_description_privacy_edited",
    "email_notification_sent",
    "file_added",
    "file_edited",
    "file_removed",
    "link_added",
    "link_edited",
    "link_removed",
    "instructions_added",
    "instructions_edited",
    "instructions_removed",
    "note_added",
    "note_edited",
    "note_deleted",
}