MONITOR_AGENCY_REQUESTS = 'monitor_agency_requests'
SPECIFIC_REQUEST_INSTRUCTIONS = 'specific_request_instructions'

AGENCY_FEATURES = [
    MONITOR_AGENCY_REQUESTS,
    SPECIFIC_REQUEST_INSTRUCTIONS
]