MONITOR_AGENCY_REQUESTS = 'monitor_agency_requests'
SPECIFIC_REQUEST_INSTRUCTIONS = 'specific_request_instructions'
CUSTOM_REQUEST_FORMS = 'custom_request_forms'

AGENCY_FEATURES = [
    MONITOR_AGENCY_REQUESTS,
    SPECIFIC_REQUEST_INSTRUCTIONS,
    CUSTOM_REQUEST_FORMS
]