ANONYMOUS = 'Anonymous User'
PUBLIC_NON_REQUESTER = 'Public User - Non-Requester'
PUBLIC_REQUESTER = 'Public User - Requester'
AGENCY_HELPER = 'Agency Helper'
AGENCY_OFFICER = 'Agency FOIL Officer'
AGENCY_ADMIN = 'Agency Administrator'
POINT_OF_CONTACT = 'point_of_contact'
