ANONYMOUS_USER = 'AnonymousUser'

AGENCY_USER = 'Saml2In:NYC Employees'
AGENCY_LDAP_USER = 'LDAP:NYC Employees'

AGENCY_USER_TYPES = frozenset((
    AGENCY_USER,
    AGENCY_LDAP_USER
))

PUBLIC_USER_NYC_ID = 'EDIRSSO'
PUBLIC_USER_FACEBOOK = 'FacebookSSO'
PUBLIC_USER_LINKEDIN = 'LinkedInSSO'
PUBLIC_USER_GOOGLE = 'GoogleSSO'
PUBLIC_USER_YAHOO = 'YahooSSO'
PUBLIC_USER_MICROSOFT = 'MSLiveSSO'

PUBLIC_USER_TYPES = frozenset((
    # user types associated with a federated identity
    PUBLIC_USER_NYC_ID,
    PUBLIC_USER_FACEBOOK,
    PUBLIC_USER_LINKEDIN,
    PUBLIC_USER_GOOGLE,
    PUBLIC_USER_YAHOO,
    PUBLIC_USER_MICROSOFT
))
