"""Renamed all table names to plural

Revision ID: 066635570e98
Revises: ea58aaea5a45
Create Date: 2016-09-24 11:53:07.961699

"""

# revision identifiers, used by Alembic.
revision = '066635570e98'
down_revision = 'ea58aaea5a45'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('agency', 'agencies')
    op.rename_table('user', 'users')
    op.rename_table('response', 'responses')
    op.rename_table('reason', 'reasons')
    op.rename_table('user_request', 'user_requests')
    op.rename_table('event', 'events')
    op.rename_table('request', 'requests')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('agencies', 'agency')
    op.rename_table('users', 'user')
    op.rename_table('responses', 'response')
    op.rename_table('reasons', 'reason')
    op.rename_table('user_requests', 'user_request')
    op.rename_table('events', 'event')
    op.rename_table('requests', 'request')
    ### end Alembic commands ###
