"""Added FOIL Officers Table

Revision ID: 0f5a03c1919d
Revises: 1f95398557cd
Create Date: 2026-04-08 15:39:16.863612

"""

# revision identifiers, used by Alembic.
revision = '0f5a03c1919d'
down_revision = '1f95398557cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foil_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('using_openrecords', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foil_officers')
    # ### end Alembic commands ###
