"""Add is_active Column to Custom Request Forms

Revision ID: 0fddd88d0a1d
Revises: 5e65ea2c1a5a
Create Date: 2023-11-03 19:48:08.761832

"""

# revision identifiers, used by Alembic.
revision = '0fddd88d0a1d'
down_revision = '5e65ea2c1a5a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_request_forms', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_request_forms', 'is_active')
    # ### end Alembic commands ###
