"""empty message

Revision ID: 106a5a534e0d
Revises: a39495c173fb
Create Date: 2016-11-04 18:37:36.911018

"""

# revision identifiers, used by Alembic.
revision = '106a5a534e0d'
down_revision = 'a39495c173fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'hash')
    ### end Alembic commands ###
