"""Updated columns previous_response_value and new_response_value to previous_value and new_value respectively in events table

Revision ID: 130672146876
Revises: 13f1878c3140
Create Date: 2016-11-02 11:19:47.768735

"""

# revision identifiers, used by Alembic.
revision = '130672146876'
down_revision = '13f1878c3140'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('new_value', postgresql.JSON(), nullable=True))
    op.add_column('events', sa.Column('previous_value', postgresql.JSON(), nullable=True))
    op.drop_column('events', 'previous_response_value')
    op.drop_column('events', 'new_response_value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('new_response_value', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('previous_response_value', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('events', 'previous_value')
    op.drop_column('events', 'new_value')
    ### end Alembic commands ###
