"""Add session_id to Users table

Revision ID: 13de5f42768b
Revises: 1920035b3a1f
Create Date: 2017-09-22 20:50:49.632841

"""

# revision identifiers, used by Alembic.
revision = "13de5f42768b"
down_revision = "1920035b3a1f"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("session_id", sa.String(length=254), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "session_id")
    ### end Alembic commands ###
