"""Added column agency_description_release_date to requests and column release_date to responses

Revision ID: 13f1878c3140
Revises: ba95e83c5e47
Create Date: 2016-11-01 15:43:34.478031

"""

# revision identifiers, used by Alembic.
revision = '13f1878c3140'
down_revision = 'ba95e83c5e47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('agency_description_release_date', sa.DateTime(), nullable=True))
    op.add_column('responses', sa.Column('release_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'release_date')
    op.drop_column('requests', 'agency_description_release_date')
    ### end Alembic commands ###
