"""140 Character Limit - File Title

Revision ID: 1920035b3a1f
Revises: 24e110b4489b
Create Date: 2017-06-24 03:09:35.487951

"""

# revision identifiers, used by Alembic.
revision = "1920035b3a1f"
down_revision = "24e110b4489b"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "title",
        existing_type=sa.VARCHAR(),
        type_=sa.String(length=140),
        existing_nullable=True,
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "title",
        existing_type=sa.String(length=140),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    ### end Alembic commands ###
