"""Add MFA

Revision ID: 199f0080036a
Revises: afde33bde2e0
Create Date: 2021-01-04 16:09:59.139962

"""

# revision identifiers, used by Alembic.
revision = '199f0080036a'
down_revision = 'afde33bde2e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa',
                    sa.Column('user_guid', sa.String(length=64), nullable=False),
                    sa.Column('secret', sa.LargeBinary(), nullable=False),
                    sa.Column('device_name', sa.String(length=32), nullable=False),
                    sa.Column('is_valid', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('user_guid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mfa')
    # ### end Alembic commands ###
