"""Events.user_id -> user_guid

Revision ID: 1e0380a553f8
Revises: b797be725719
Create Date: 2016-12-17 15:34:41.921453

"""

# revision identifiers, used by Alembic.
revision = '1e0380a553f8'
down_revision = 'b797be725719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_guid', sa.String(length=64), nullable=True))
    op.drop_constraint('events_user_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['user_guid', 'auth_user_type'], ['guid', 'auth_user_type'])
    op.drop_column('events', 'user_id')
    op.alter_column('users', 'terms_of_use_accepted',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'terms_of_use_accepted',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.add_column('events', sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_user_id_fkey', 'events', 'users', ['user_id', 'auth_user_type'], ['guid', 'auth_user_type'])
    op.drop_column('events', 'user_guid')
    ### end Alembic commands ###
