"""Events table index

Revision ID: 1f95398557cd
Revises: 0fddd88d0a1d
Create Date: 2024-05-23 22:38:42.760122

"""

# revision identifiers, used by Alembic.
revision = '1f95398557cd'
down_revision = '0fddd88d0a1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_request_id'), 'events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_request_id'), table_name='events')
    # ### end Alembic commands ###
