"""initial migration with all fk and tables

Revision ID: 2098ee909eaa
Revises: None
Create Date: 2016-09-09 12:03:37.838741

"""

# revision identifiers, used by Alembic.
revision = '2098ee909eaa'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('ein', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('next_request_number', sa.Integer(), nullable=True),
    sa.Column('default_email', sa.String(length=254), nullable=True),
    sa.Column('appeal_email', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('ein')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('guid', sa.String(length=1000), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email_validated', sa.Boolean(), nullable=False),
    sa.Column('terms_of_use_accepted', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('fax_number', sa.String(length=15), nullable=True),
    sa.Column('mailing_address', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('guid', 'user_type'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('request',
    sa.Column('id', sa.String(length=19), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('agency', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('submission', sa.String(length=30), nullable=True),
    sa.Column('current_status', sa.Enum('Open', 'In Progress', 'Due Soon', 'Overdue', 'Closed', 'Re-Opened', name='statuses'), nullable=True),
    sa.Column('visibility', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agency'], ['agency.ein'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=19), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('content', postgresql.JSON(), nullable=True),
    sa.Column('privacy', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_request',
    sa.Column('user_guid', sa.String(length=1000), nullable=False),
    sa.Column('request_id', sa.String(length=19), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('user_guid', 'request_id')
    )
    op.create_table('event',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=19), nullable=True),
    sa.Column('user_id', sa.String(length=1000), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('previous_response_value', sa.String(length=5000), nullable=True),
    sa.Column('new_response_value', sa.String(length=50000), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('user_request')
    op.drop_table('response')
    op.drop_table('request')
    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('agency')
    ### end Alembic commands ###
