"""Initial migration with users and sessions

Revision ID: 277d1f2e8a5d
Revises: None
Create Date: 2016-08-31 12:16:15.703626

"""

# revision identifiers, used by Alembic.
revision = '277d1f2e8a5d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    ### end Alembic commands ###
