"""Added category to agency table, agency fk to user table, and created reason table

Revision ID: 35e1f2ab8b20
Revises: 2098ee909eaa
Create Date: 2016-09-12 10:00:19.419079

"""

# revision identifiers, used by Alembic.
revision = '35e1f2ab8b20'
down_revision = '2098ee909eaa'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reason',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('agency', sa.Integer(), nullable=True),
                    sa.Column('deny_reason', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['agency'], ['agency.ein'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('agency', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('agency', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'agency', ['agency'], ['ein'])
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'agency')
    op.drop_column('agency', 'category')
    op.create_table('users',
                    sa.Column('guid', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
                    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
                    sa.Column('middle_initial', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
                    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('email_validated', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('terms_of_use_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('user_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('company', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
                    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
                    sa.Column('fax_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
                    sa.Column('mailing_address', postgresql.JSON(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('guid', name='users_pkey')
                    )
    op.drop_table('reason')
    ### end Alembic commands ###
