"""Added agency_description column to requests table

Revision ID: 3d3b2c178f4e
Revises: fa0cc904ac83
Create Date: 2016-10-05 15:38:49.979995

"""

# revision identifiers, used by Alembic.
revision = '3d3b2c178f4e'
down_revision = 'fa0cc904ac83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('agency_description', sa.String(length=5000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'agency_description')
    ### end Alembic commands ###
