"""Created new tables for separate response types and updated responses table

Revision ID: 3dd0c7508921
Revises: 96a9d8c1cb5c
Create Date: 2016-09-29 11:22:46.504924

"""

# revision identifiers, used by Alembic.
revision = '3dd0c7508921'
down_revision = '96a9d8c1cb5c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('metadata_id', sa.Integer(), nullable=True))
    op.drop_column('responses', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('content', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('responses', 'metadata_id')
    ### end Alembic commands ###
