"""Added Minimum Required to Custom Request Forms

Revision ID: 40606de33855
Revises: dc926c74551d
Create Date: 2018-06-11 14:04:41.472099

"""

# revision identifiers, used by Alembic.
revision = '40606de33855'
down_revision = 'dc926c74551d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_request_forms', sa.Column('minimum_required', sa.Integer(), nullable=True))
    op.alter_column('custom_request_forms', 'form_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_request_forms', 'form_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('custom_request_forms', 'minimum_required')
    ### end Alembic commands ###
