"""Added Agency Acronym to DB

Revision ID: 58a5abdd94ac
Revises: 971f341c0204
Create Date: 2017-06-09 22:00:35.278382

"""

# revision identifiers, used by Alembic.
revision = "58a5abdd94ac"
down_revision = "52a4062502bb"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agencies", sa.Column("acronym", sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agencies", "acronym")
    ### end Alembic commands ###
