"""Adding User class to models

Revision ID: 58f17f46c994
Revises: None
Create Date: 2016-08-31 10:44:33.371924

"""

# revision identifiers, used by Alembic.
revision = '58f17f46c994'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('guid', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email_validated', sa.Boolean(), nullable=False),
    sa.Column('terms_of_use_accepted', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('fax_number', sa.String(length=15), nullable=True),
    sa.Column('mailing_address', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
