"""Added need_additional_details to Reasons
Revision ID: 5bb24f92ca63
Revises: afde33bde2e0
Create Date: 2021-04-20 21:14:10.825678
"""

# revision identifiers, used by Alembic.
revision = '5bb24f92ca63'
down_revision = 'afde33bde2e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons', sa.Column('need_additional_details', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reasons', 'need_additional_details')
    # ### end Alembic commands ###