"""Added need_additional_details to Reasons

Revision ID: 5bb24f92ca63
Revises: afde33bde2e0
Create Date: 2021-04-20 21:14:10.825678

"""

# revision identifiers, used by Alembic.
revision = '5bb24f92ca63'
down_revision = 'afde33bde2e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_user_requests')
    op.drop_table('user_requests_check')
    op.drop_table('removed')
    op.create_foreign_key(None, 'agency_users', 'users', ['user_guid'], ['guid'])
    op.add_column('reasons', sa.Column('need_additional_details', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('reasons', 'need_additional_details')
    op.drop_constraint(None, 'agency_users', type_='foreignkey')
    op.create_table('removed',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('user_requests_check',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('missing_user_requests',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
