"""Add Order column to Custom Request Forms

Revision ID: 5e65ea2c1a5a
Revises: 19223de796a5
Create Date: 2023-06-01 16:36:05.167812

"""

# revision identifiers, used by Alembic.
revision = '5e65ea2c1a5a'
down_revision = '19223de796a5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_request_forms', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_request_forms', 'order')
    # ### end Alembic commands ###
