"""Changed column 'attachments' to 'linked_files' in emails table

Revision ID: 653b37144c10
Revises: 3d3b2c178f4e
Create Date: 2016-10-13 16:45:14.747069

"""

# revision identifiers, used by Alembic.
revision = '653b37144c10'
down_revision = '3d3b2c178f4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('linked_files', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('emails', 'attachments')
    op.drop_constraint('users_guid_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_guid_key', 'users', ['guid'])
    op.add_column('emails', sa.Column('attachments', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('emails', 'linked_files')
    ### end Alembic commands ###
