"""add title to reasons

Revision ID: 66fc2a1daa1f
Revises: b797be725719
Create Date: 2016-12-16 12:31:14.345102

"""

# revision identifiers, used by Alembic.
revision = '66fc2a1daa1f'
down_revision = 'b797be725719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons', sa.Column('title', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reasons', 'title')
    ### end Alembic commands ###
