"""Adding agency_features column; Removing monitors_sub_agencies

Revision ID: 6b6c86011ff8
Revises: d45f51ec6bab
Create Date: 2017-05-24 17:26:08.930161

"""

# revision identifiers, used by Alembic.
revision = '6b6c86011ff8'
down_revision = 'd45f51ec6bab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('agency_features', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('agencies', 'monitors_sub_agencies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('monitors_sub_agencies', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('agencies', 'agency_features')
    ### end Alembic commands ###
