"""Add Signature to Users

Revision ID: 7ba6fbb131bb
Revises: c72d576b93f3
Create Date: 2018-03-29 18:35:45.474745

"""

# revision identifiers, used by Alembic.
revision = "7ba6fbb131bb"
down_revision = "9005ab594598"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("signature", sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "signature")
    ### end Alembic commands ###
