"""update to enum agency_user

Revision ID: 7cea3b20684b
Revises: 9908a9bf1dbd
Create Date: 2017-06-21 17:11:01.739824

"""

# revision identifiers, used by Alembic.
revision = '7cea3b20684b'
down_revision = '9908a9bf1dbd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency_users', 'auth_user_type',
               existing_type=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'),
               type_=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'))
    op.alter_column('events', 'auth_user_type',
               existing_type=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'),
               type_=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'),
               existing_nullable=True)
    op.alter_column('user_requests', 'auth_user_type',
               existing_type=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'),
               type_=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'))
    op.alter_column('users', 'auth_user_type',
               existing_type=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'),
               type_=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_user_type',
               existing_type=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'),
               type_=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'))
    op.alter_column('user_requests', 'auth_user_type',
               existing_type=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'),
               type_=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'))
    op.alter_column('events', 'auth_user_type',
               existing_type=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'),
               type_=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'),
               existing_nullable=True)
    op.alter_column('agency_users', 'auth_user_type',
               existing_type=sa.Enum('EDIRSSO', 'EDIRSSO', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'None', 'AnonymousUser', name='auth_user_type'),
               type_=postgresql.ENUM('Saml2In:NYC Employees', 'LDAP:NYC Employees', 'FacebookSSO', 'MSLiveSSO', 'YahooSSO', 'LinkedInSSO', 'GoogleSSO', 'EDIRSSO', 'AnonymousUser', name='auth_user_type'))
    ### end Alembic commands ###
