"""Add MFA

Revision ID: 84a8fa98bdf2
Revises: afde33bde2e0
Create Date: 2021-01-15 14:19:41.812334

"""

# revision identifiers, used by Alembic.
revision = '84a8fa98bdf2'
down_revision = 'afde33bde2e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_guid', sa.String(length=64), nullable=True),
                    sa.Column('secret', sa.LargeBinary(), nullable=False),
                    sa.Column('device_name', sa.String(length=32), nullable=False),
                    sa.Column('is_valid', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mfa')
    # ### end Alembic commands ###
