"""Added user_type to user_requests table

Revision ID: 8750ca13e694
Revises: 066635570e98
Create Date: 2016-09-24 12:37:26.339165

"""

# revision identifiers, used by Alembic.
revision = '8750ca13e694'
down_revision = '066635570e98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_requests', sa.Column('user_type', sa.String(length=64), nullable=False))
    op.drop_constraint('user_requests_user_guid_fkey', 'user_requests', type_='foreignkey')
    op.create_foreign_key(None, 'user_requests', 'users', ['user_guid', 'user_type'], ['guid', 'user_type'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_requests', type_='foreignkey')
    op.create_foreign_key('user_requests_user_guid_fkey', 'user_requests', 'users', ['user_guid'], ['guid'])
    op.drop_column('user_requests', 'user_type')
    ### end Alembic commands ###
