"""Add LetterTemplates

Revision ID: 9005ab594598
Revises: 949aebe9e480
Create Date: 2018-03-20 18:41:57.143317

"""

# revision identifiers, used by Alembic.
revision = "9005ab594598"
down_revision = "949aebe9e480"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "letter_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "acknowledgment",
                "extension",
                "closing",
                "denial",
                "re-opening",
                "letters",
                name="letter_type",
            ),
            nullable=False,
        ),
        sa.Column("agency_ein", sa.String(length=4), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agency_ein"], ["agencies.ein"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("letter_templates")
    ### end Alembic commands ###
