"""Letters table

Revision ID: 949aebe9e480
Revises: 13de5f42768b
Create Date: 2018-03-19 17:31:30.182191

"""

# revision identifiers, used by Alembic.
revision = "949aebe9e480"
down_revision = "13de5f42768b"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "letters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["responses.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("letters")
    ### end Alembic commands ###
