"""Changed column permission to permissions in user_requests table

Revision ID: 96a9d8c1cb5c
Revises: 8750ca13e694
Create Date: 2016-09-24 13:24:44.949214

"""

# revision identifiers, used by Alembic.
revision = '96a9d8c1cb5c'
down_revision = '8750ca13e694'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_requests', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('user_requests', 'permission')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_requests', sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_requests', 'permissions')
    ### end Alembic commands ###
