"""Changed 'visibility' column in requests table to be 'privacy'

Revision ID: a11a7c0298e8
Revises: 653b37144c10
Create Date: 2016-10-15 09:43:39.493285

"""

# revision identifiers, used by Alembic.
revision = 'a11a7c0298e8'
down_revision = '653b37144c10'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('privacy', postgresql.JSON(), nullable=True))
    op.drop_column('requests', 'visibility')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('visibility', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('requests', 'privacy')
    ### end Alembic commands ###
