"""add agency user

Revision ID: a75c148b3751
Revises: ab1a59fd2469
Create Date: 2016-12-09 18:22:21.150350

"""

# revision identifiers, used by Alembic.
revision = 'a75c148b3751'
down_revision = 'ab1a59fd2469'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'administrators')
    op.add_column('users', sa.Column('agency_ein', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_agency_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_agency_admin', sa.Boolean(), nullable=False))
    op.drop_constraint('users_agency_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'agencies', ['agency_ein'], ['ein'])
    op.drop_column('users', 'agency')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_agency_fkey', 'users', 'agencies', ['agency'], ['ein'])
    op.drop_column('users', 'is_agency_admin')
    op.drop_column('users', 'is_agency_active')
    op.drop_column('users', 'agency_ein')
    op.add_column('agencies', sa.Column('administrators', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    ### end Alembic commands ###
