"""add response_tokens

Revision ID: a8ba6e3e13ad
Revises: 106a5a534e0d
Create Date: 2016-11-09 10:00:02.120531

"""

# revision identifiers, used by Alembic.
revision = 'a8ba6e3e13ad'
down_revision = '106a5a534e0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_tokens')
    ### end Alembic commands ###
