"""Added is_read_only to Agency Users Table

Revision ID: a9d6b5037034
Revises: 5bb24f92ca63
Create Date: 2021-10-13 19:42:33.164658

"""

# revision identifiers, used by Alembic.
revision = 'a9d6b5037034'
down_revision = '5bb24f92ca63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_users', sa.Column('is_read_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_users', 'is_read_only')
    # ### end Alembic commands ###
