"""Updated user table to include data from SAML

Revision ID: aed2d63a7335
Revises: 35e1f2ab8b20
Create Date: 2016-09-19 16:49:53.667374

"""

# revision identifiers, used by Alembic.
revision = 'aed2d63a7335'
down_revision = '35e1f2ab8b20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization', sa.String(length=128), nullable=True))
    op.drop_column('user', 'company')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'organization')
    ### end Alembic commands ###
