"""Removed character limit on Notes

Revision ID: afde33bde2e0
Revises: b12d4ba1cfd4
Create Date: 2020-04-29 17:07:10.341149

"""

# revision identifiers, used by Alembic.
revision = 'afde33bde2e0'
down_revision = 'b12d4ba1cfd4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('removed')
    op.drop_table('user_requests_check')
    op.drop_table('missing_user_requests')
    op.create_foreign_key(None, 'agency_users', 'users', ['user_guid'], ['guid'])
    op.create_unique_constraint(None, 'users', ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'agency_users', type_='foreignkey')
    op.create_table('missing_user_requests',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('user_requests_check',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('removed',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('added_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
