"""Removed character limit on Notes

Revision ID: afde33bde2e0
Revises: b12d4ba1cfd4
Create Date: 2020-04-29 17:07:10.341149

"""

# revision identifiers, used by Alembic.
revision = 'afde33bde2e0'
down_revision = 'b12d4ba1cfd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.VARCHAR,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR,
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###
