"""Add Envelope Functionality

Revision ID: b3c0c76ac2e6
Revises: c7f05adcf7d9
Create Date: 2018-04-06 20:17:17.556595

"""

# revision identifiers, used by Alembic.
revision = "b3c0c76ac2e6"
down_revision = "c7f05adcf7d9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "envelope_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_ein", sa.String(length=4), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agency_ein"], ["agencies.ein"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "envelopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("latex", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["responses.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("envelopes")
    op.drop_table("envelope_templates")
    ### end Alembic commands ###
