"""Added Minimum Required To Custom Request Forms

Revision ID: b722969f38a6
Revises: 60116f094400
Create Date: 2018-07-02 15:52:43.523667

"""

# revision identifiers, used by Alembic.
revision = "b722969f38a6"
down_revision = "60116f094400"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_request_forms",
        sa.Column("minimum_required", sa.Integer(), nullable=True),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_request_forms", "minimum_required")
    ### end Alembic commands ###
