"""add super users

Revision ID: b797be725719
Revises: 507446fcc028
Create Date: 2016-12-14 17:52:55.374990

"""

# revision identifiers, used by Alembic.
revision = 'b797be725719'
down_revision = '507446fcc028'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super')
    ### end Alembic commands ###
