"""Terms of Use Accepted is a string

Revision ID: b8dc8d84284f
Revises: aed2d63a7335
Create Date: 2016-09-20 21:25:48.937626

"""

# revision identifiers, used by Alembic.
revision = 'b8dc8d84284f'
down_revision = 'aed2d63a7335'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'terms_of_use_accepted',
                    existing_type=sa.BOOLEAN(),
                    type_=sa.String(16),
                    nullable = True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'terms_of_use_accepted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    ### end Alembic commands ###
