"""Link Communication to Determinations

Revision ID: c72d576b93f3
Revises: 9005ab594598
Create Date: 2018-03-28 18:08:32.918277

"""

# revision identifiers, used by Alembic.
revision = 'c72d576b93f3'
down_revision = '9005ab594598'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    communication_method_type = postgresql.ENUM('letters', 'emails', name='communication_method_type')
    communication_method_type.create(op.get_bind())

    op.add_column('determinations', sa.Column('communication_method_id', sa.Integer(), nullable=True))
    op.add_column('determinations',
                  sa.Column('communication_method_type',
                            sa.Enum('letters', 'emails', name='communication_method_type'),
                            nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('determinations', 'communication_method_type')
    op.drop_column('determinations', 'communication_method_id')

    communication_method_type = postgresql.ENUM('letters', 'emails', name='communication_method_type')
    communication_method_type.drop(op.get_bind())
    ### end Alembic commands ###
