"""altered_reasons

Revision ID: d19388e28897
Revises: fc3748f88edb
Create Date: 2016-11-18 14:54:23.479101

"""

# revision identifiers, used by Alembic.
revision = 'd19388e28897'
down_revision = 'fc3748f88edb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reasons', sa.Column('agency_ein', sa.Integer(), nullable=True))
    op.add_column('reasons', sa.Column('content', sa.String(), nullable=False))
    op.add_column('reasons', sa.Column('type', sa.Enum('closing', 'denial', name='reason_type'), nullable=False))
    op.drop_constraint('reasons_agency_fkey', 'reasons', type_='foreignkey')
    op.create_foreign_key(None, 'reasons', 'agencies', ['agency_ein'], ['ein'])
    op.drop_column('reasons', 'agency')
    op.drop_column('reasons', 'deny_reason')
    op.alter_column('responses', 'type',
               existing_type=postgresql.ENUM('notes', 'links', 'files', 'instructions', 'extensions', 'emails', name='type'),
               type_=sa.Enum('notes', 'links', 'files', 'instructions', 'determinations', 'emails', name='type'),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'type',
               existing_type=sa.Enum('notes', 'links', 'files', 'instructions', 'determinations', 'emails', name='type'),
               type_=postgresql.ENUM('notes', 'links', 'files', 'instructions', 'extensions', 'emails', name='type'),
               existing_nullable=True)
    op.add_column('reasons', sa.Column('deny_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reasons', sa.Column('agency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reasons', type_='foreignkey')
    op.create_foreign_key('reasons_agency_fkey', 'reasons', 'agencies', ['agency'], ['ein'])
    op.drop_column('reasons', 'type')
    op.drop_column('reasons', 'content')
    op.drop_column('reasons', 'agency_ein')
    ### end Alembic commands ###
