"""Moving monitor_sub_agencies to a feature flag

Revision ID: d45f51ec6bab
Revises: 85068c55138a
Create Date: 2017-05-23 23:06:18.323074

"""

# revision identifiers, used by Alembic.
revision = 'd45f51ec6bab'
down_revision = '85068c55138a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('monitors_sub_agencies', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'monitors_sub_agencies')
    ### end Alembic commands ###
