"""Add MFA

Revision ID: d97f97be6905
Revises: afde33bde2e0
Create Date: 2020-12-07 17:05:32.720959

"""

# revision identifiers, used by Alembic.
revision = 'd97f97be6905'
down_revision = 'afde33bde2e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa',
                    sa.Column('user_guid', sa.String(length=64), nullable=False),
                    sa.Column('secret', sa.String(length=32), nullable=False),
                    sa.Column('device_name', sa.String(length=32), nullable=False),
                    sa.Column('is_valid', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ),
                    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('user_guid')
                    )
    op.create_foreign_key(None, 'agency_users', 'users', ['user_guid'], ['guid'])
    op.create_unique_constraint(None, 'users', ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'agency_users', type_='foreignkey')
    op.drop_table('mfa')
    # ### end Alembic commands ###
