"""Added Category to Custom Request Forms

Revision ID: dc926c74551d
Revises: 7e0434686370
Create Date: 2018-06-07 19:02:12.784012

"""

# revision identifiers, used by Alembic.
revision = "dc926c74551d"
down_revision = "7e0434686370"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_request_forms", sa.Column("category", sa.Integer(), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_request_forms", "category")
    ### end Alembic commands ###
