"""Remove request_id, response_id, and privacy columns in separate responses tables

Revision ID: e5b756ac4523
Revises: 3dd0c7508921
Create Date: 2016-09-29 14:26:22.688385

"""

# revision identifiers, used by Alembic.
revision = 'e5b756ac4523'
down_revision = '3dd0c7508921'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emails_request_id_fkey', 'emails', type_='foreignkey')
    op.drop_constraint('emails_response_id_fkey', 'emails', type_='foreignkey')
    op.drop_column('emails', 'privacy')
    op.drop_column('emails', 'request_id')
    op.drop_column('emails', 'response_id')
    op.drop_constraint('extensions_response_id_fkey', 'extensions', type_='foreignkey')
    op.drop_constraint('extensions_request_id_fkey', 'extensions', type_='foreignkey')
    op.drop_column('extensions', 'privacy')
    op.drop_column('extensions', 'request_id')
    op.drop_column('extensions', 'response_id')
    op.drop_constraint('files_response_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_request_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'privacy')
    op.drop_column('files', 'request_id')
    op.drop_column('files', 'response_id')
    op.drop_constraint('instructions_request_id_fkey', 'instructions', type_='foreignkey')
    op.drop_constraint('instructions_response_id_fkey', 'instructions', type_='foreignkey')
    op.drop_column('instructions', 'privacy')
    op.drop_column('instructions', 'request_id')
    op.drop_column('instructions', 'response_id')
    op.drop_constraint('links_response_id_fkey', 'links', type_='foreignkey')
    op.drop_constraint('links_request_id_fkey', 'links', type_='foreignkey')
    op.drop_column('links', 'privacy')
    op.drop_column('links', 'request_id')
    op.drop_column('links', 'response_id')
    op.drop_constraint('notes_request_id_fkey', 'notes', type_='foreignkey')
    op.drop_constraint('notes_response_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'privacy')
    op.drop_column('notes', 'request_id')
    op.drop_column('notes', 'response_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_response_id_fkey', 'notes', 'responses', ['response_id'], ['id'])
    op.create_foreign_key('notes_request_id_fkey', 'notes', 'requests', ['request_id'], ['id'])
    op.add_column('links', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('links_request_id_fkey', 'links', 'requests', ['request_id'], ['id'])
    op.create_foreign_key('links_response_id_fkey', 'links', 'responses', ['response_id'], ['id'])
    op.add_column('instructions', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('instructions', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('instructions', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('instructions_response_id_fkey', 'instructions', 'responses', ['response_id'], ['id'])
    op.create_foreign_key('instructions_request_id_fkey', 'instructions', 'requests', ['request_id'], ['id'])
    op.add_column('files', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('files_request_id_fkey', 'files', 'requests', ['request_id'], ['id'])
    op.create_foreign_key('files_response_id_fkey', 'files', 'responses', ['response_id'], ['id'])
    op.add_column('extensions', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('extensions', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('extensions', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('extensions_request_id_fkey', 'extensions', 'requests', ['request_id'], ['id'])
    op.create_foreign_key('extensions_response_id_fkey', 'extensions', 'responses', ['response_id'], ['id'])
    op.add_column('emails', sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('request_id', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('privacy', postgresql.ENUM('private', 'public', name='privacy'), autoincrement=False, nullable=True))
    op.create_foreign_key('emails_response_id_fkey', 'emails', 'responses', ['response_id'], ['id'])
    op.create_foreign_key('emails_request_id_fkey', 'emails', 'requests', ['request_id'], ['id'])
    ### end Alembic commands ###
