"""Added user_type column to Event table

Revision ID: ea58aaea5a45
Revises: ec22caf3d478
Create Date: 2016-09-24 10:33:36.746747

"""

# revision identifiers, used by Alembic.
revision = 'ea58aaea5a45'
down_revision = 'ec22caf3d478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_type', sa.String(length=64), nullable=True))
    op.drop_constraint('event_user_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['user_id', 'user_type'], ['guid', 'user_type'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_user_id_fkey', 'event', 'user', ['user_id'], ['guid'])
    op.drop_column('event', 'user_type')
    ### end Alembic commands ###
