"""Changed appeal_email to appeals_email

Revision ID: ec22caf3d478
Revises: b8dc8d84284f
Create Date: 2016-09-21 16:27:06.176391

"""

# revision identifiers, used by Alembic.
revision = 'ec22caf3d478'
down_revision = 'b8dc8d84284f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('appeals_email', sa.String(length=254), nullable=True))
    op.drop_column('agency', 'appeal_email')
    op.alter_column('agency', 'name',
                   existing_type=sa.String(64),
                   type_=sa.String(256),
                   nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('appeal_email', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    op.drop_column('agency', 'appeals_email')
    ### end Alembic commands ###
