UNSAFE_NEXT_URL = "The provided login redirect url is unsafe."
EMAIL_STATUS_CHECK_FAILURE = "Failed to check email validation status."
TOU_STATUS_CHECK_FAILURE = "Failed to check terms of use version."
ENROLLMENT_STATUS_CHECK_FAILURE = "Failed to check enrollment status."
ENROLLMENT_FAILURE = "Failed to enroll."
UNENROLLMENT_FAILURE = "Failed to un-enroll."
REVOKE_TOKEN_FAILURE = "Failed to revoke access token."
USER_DATA_RETRIEVAL_FAILURE = "Unable to get user data from API."